# Generated by Django 4.2.29 on 2026-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_stockmaintenance_stockpurchase_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-start_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='approved_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='project_owner',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='project_status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='activity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_by_month',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='drawn_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='drawn_by_month',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='no_of_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='task',
            name='order_value_omr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='project_id_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='project_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='proposal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='revision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
