# Generated by Django 4.2.29 on 2026-05-06 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_notification_read_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCECostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lce_cost_details', to='erp_app.project')),
                ('cost_head', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reference_note', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
