# Generated by Django 4.2.29 on 2026-05-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0003_lcecostdetail_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commentnotificationread',
            new_name='erp_app_com_user_id_5e6488_idx',
            old_name='erp_app_com_user_id_9de16e_idx',
        ),
        migrations.RenameIndex(
            model_name='commentnotificationread',
            new_name='erp_app_com_user_id_94e5cc_idx',
            old_name='erp_app_com_user_id_8ab3ec_idx',
        ),
        migrations.RenameIndex(
            model_name='tasknotificationread',
            new_name='erp_app_tas_user_id_007263_idx',
            old_name='erp_app_tas_user_id_a0b066_idx',
        ),
        migrations.RenameIndex(
            model_name='tasknotificationread',
            new_name='erp_app_tas_user_id_1e4e73_idx',
            old_name='erp_app_tas_user_id_ebc510_idx',
        ),
    ]
