# Generated by Django 4.2.29 on 2026-03-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0003_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='serial_no',
        ),
    ]
