# Generated by Django 4.2.29 on 2026-06-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		("erp_app", "0006_approvalstatus_info"),
	]

	operations = [
		migrations.CreateModel(
			name="ProjectLayoutDrawing",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("drawing_name", models.CharField(blank=True, max_length=255)),
				("level_one_message", models.TextField(blank=True)),
				("level_two_message", models.TextField(blank=True)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				(
					"level_one_status",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="layout_drawing_level_one_statuses",
						to="erp_app.approvalstatus_info",
					),
				),
				(
					"level_two_status",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="layout_drawing_level_two_statuses",
						to="erp_app.approvalstatus_info",
					),
				),
				(
					"project",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="layout_drawings",
						to="erp_app.project",
					),
				),
			],
			options={
				"ordering": ["id"],
			},
		),
		migrations.CreateModel(
			name="ProjectLayoutDrawingAttachment",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("file", models.FileField(upload_to="project_layout_drawings/%Y/%m/%d")),
				("original_name", models.CharField(blank=True, max_length=255)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				(
					"drawing",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="attachments",
						to="erp_app.projectlayoutdrawing",
					),
				),
			],
			options={
				"ordering": ["created_at", "id"],
			},
		),
	]

