# Generated by Django 4.2.29 on 2026-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0007_title_case_backfill_remaining_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaintenanceTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmaintenance',
            name='movement_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
