# Generated by Django 4.2.29 on 2026-03-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0008_stockmaintenancetypeoption_alter_project_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLifecycleStatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
