# Generated by Django 4.2.29 on 2026-03-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0010_seed_task_and_project_status_defaults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='expected_customer_need_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='client_name',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
