# Generated by Django 4.2.29 on 2026-03-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0011_rename_project_fields_add_expected_customer_need_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project_no',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='erp_app.project'),
        ),
    ]
