# Generated by Django 4.2.29 on 2026-03-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0013_seed_default_option_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_status',
        ),
    ]
