# Generated by Django 4.2.29 on 2026-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0015_project_status_fk_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
