# Generated by Django 4.2.29 on 2026-03-21 16:55

from django.db import migrations

DEFAULT_GROUPS = ["Admin", "Manager", "Engineer", "User"]


def seed_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in DEFAULT_GROUPS:
        Group.objects.get_or_create(name=name)


def reverse_seed_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=DEFAULT_GROUPS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0018_user_status_option_and_profile'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(seed_groups, reverse_seed_groups),
    ]
