# Generated by Django 4.2.29 on 2026-03-21 17:07

from django.db import migrations

GROUPS_TO_REMOVE = ["Manager", "Engineer"]


def remove_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=GROUPS_TO_REMOVE).delete()


def restore_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in GROUPS_TO_REMOVE:
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("erp_app", "0019_seed_default_groups"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(remove_groups, restore_groups),
    ]
