# Generated by Django 4.2.29 on 2026-03-23 00:00

import os

from django.db import migrations, models


def _import_timesheet_activities_from_excel(apps, schema_editor):
    TimeSheetActivity = apps.get_model("erp_app", "TimeSheetActivity")
    from django.conf import settings

    excel_path = os.path.join(str(settings.BASE_DIR), "erp_app", "media", "time_sheet.xlsx")
    if not os.path.exists(excel_path):
        return

    try:
        import openpyxl
    except ImportError:
        return

    wb = openpyxl.load_workbook(excel_path, data_only=True)
    ws = wb.active
    seen = set()
    for row in ws.iter_rows(min_row=2, values_only=True):
        raw = row[3] if len(row) > 3 else None  # Column D = Activity
        if raw in (None, ""):
            continue
        normalized = str(raw).strip()
        normalized = " ".join(normalized.split())
        normalized = normalized.title()
        if not normalized:
            continue
        key = normalized.lower()
        if key in seen:
            continue
        seen.add(key)
        TimeSheetActivity.objects.get_or_create(name=normalized)


def _reverse_import(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("erp_app", "0022_add_activity_model_and_import_from_excel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSheetActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={"verbose_name_plural": "timesheet activities", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="TimeSheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_name", models.CharField(max_length=255)),
                ("billing_date", models.DateField()),
                ("efforts", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(on_delete=models.PROTECT, related_name="timesheets", to="erp_app.timesheetactivity"),
                ),
                (
                    "task",
                    models.ForeignKey(on_delete=models.PROTECT, related_name="timesheets", to="erp_app.task"),
                ),
            ],
            options={"ordering": ["-billing_date", "-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="timesheet",
            constraint=models.UniqueConstraint(
                fields=("employee_name", "activity", "billing_date"),
                name="uniq_timesheet_emp_activity_billing_date",
            ),
        ),
        migrations.RunPython(_import_timesheet_activities_from_excel, _reverse_import),
    ]

