# Generated by Django 4.2.29 on 2026-03-25 00:00

from django.db import migrations, models


def _dedupe_timesheet_rows(apps, schema_editor):
    TimeSheet = apps.get_model("erp_app", "TimeSheet")

    # Keep the newest row (highest id) for each employee/task/billing_date combo.
    seen = set()
    duplicate_ids = []
    for row in TimeSheet.objects.order_by("-id").values("id", "employee_name", "task_id", "billing_date"):
        key = (row["employee_name"], row["task_id"], row["billing_date"])
        if key in seen:
            duplicate_ids.append(row["id"])
            continue
        seen.add(key)

    if duplicate_ids:
        TimeSheet.objects.filter(id__in=duplicate_ids).delete()


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("erp_app", "0023_add_timesheet_models"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timesheet",
            name="uniq_timesheet_emp_activity_billing_date",
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="activity",
        ),
        migrations.RunPython(_dedupe_timesheet_rows, _noop_reverse),
        migrations.DeleteModel(
            name="TimeSheetActivity",
        ),
        migrations.AddConstraint(
            model_name="timesheet",
            constraint=models.UniqueConstraint(
                fields=("employee_name", "task", "billing_date"),
                name="uniq_timesheet_emp_task_billing_date",
            ),
        ),
    ]



