"""
Django settings for erp project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import re
import socket
import subprocess
from ipaddress import ip_address
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z)m$9_v15g0%$cp070y8fsu4)l6u1&4zb@p%d9@1ie@tgg!=6e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

def _discover_private_ipv4_hosts() -> list[str]:
    """Collect current LAN IPv4 addresses so host checks survive DHCP IP changes."""
    hosts = {"127.0.0.1", "localhost", "0.0.0.0"}
    try:
        for ip in socket.gethostbyname_ex(socket.gethostname())[2]:
            try:
                if ip_address(ip).is_private:
                    hosts.add(ip)
            except ValueError:
                continue
    except OSError:
        pass

    # Windows fallback: hostname lookup may return only one adapter address.
    try:
        output = subprocess.check_output(["ipconfig"], text=True, encoding="utf-8", errors="ignore")
        for ip in re.findall(r"IPv4[^:]*:\s*(\d+\.\d+\.\d+\.\d+)", output):
            try:
                if ip_address(ip).is_private:
                    hosts.add(ip)
            except ValueError:
                continue
    except Exception:
        pass

    return sorted(hosts)


_default_allowed_hosts = set(_discover_private_ipv4_hosts())
_env_allowed_hosts = {
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if h.strip()
}
ALLOWED_HOSTS = sorted(_default_allowed_hosts | _env_allowed_hosts)

# For LAN testing, avoid Invalid HTTP_HOST when DHCP changes local IP.
# IMPORTANT: For production/service deployment, always allow all hosts in DEBUG mode
if DEBUG:
    ALLOWED_HOSTS = ["*"]
elif os.getenv("DJANGO_STRICT_HOST_CHECK", "0") != "1":
    ALLOWED_HOSTS = ["*"]

_default_csrf_origins = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://192.168.1.6:8000",
]
for host in ALLOWED_HOSTS:
    if host not in {"localhost", "0.0.0.0"}:
        _default_csrf_origins.append(f"http://{host}:8000")

_env_csrf_origins = {
    o.strip()
    for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
}
CSRF_TRUSTED_ORIGINS = sorted(set(_default_csrf_origins) | _env_csrf_origins)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'erp_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'erp_001',
        'USER': 'postgres',
        'PASSWORD': '244613',
        'HOST': 'localhost'
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dist',
]
WHITENOISE_INDEX_FILE = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
