from django.urls import path
from .views import (
    csrf_token_view,
    approve_registration_api_view,
    create_project_api_view,
    create_project_lifecycle_status_option_api_view,
    create_vendor_api_view,
    list_users_api_view,
    list_pending_registrations_api_view,
    list_projects_api_view,
    list_project_lifecycle_meta_api_view,
    list_vendors_api_view,
    login_api_view,
    logout_api_view,
    forgot_password_api_view,
    reset_password_api_view,
    project_detail_api_view,
    register_api_view,
    register_meta_api_view,
    user_detail_api_view,
    vendor_detail_api_view,
    list_stock_purchases_api_view,
    create_stock_purchase_api_view,
    stock_purchase_detail_api_view,
    list_stock_maintenance_api_view,
    list_stock_maintenance_meta_api_view,
    create_stock_maintenance_api_view,
    create_stock_maintenance_type_option_api_view,
    stock_maintenance_detail_api_view,
    list_tasks_api_view,
    list_task_meta_api_view,
    create_task_api_view,
    download_task_template_api_view,
    import_tasks_excel_api_view,
    task_detail_api_view,
    create_task_status_option_api_view,
    create_activity_option_api_view,
    create_project_status_option_api_view,
    create_cdc_team_expense_api_view,
    create_expense_item_option_api_view,
    create_expense_session_option_api_view,
    create_expense_status_option_api_view,
    list_timesheet_meta_api_view,
    list_timesheets_api_view,
    list_cdc_team_expense_meta_api_view,
    list_cdc_team_expenses_api_view,
    create_timesheet_api_view,
    cdc_team_expense_detail_api_view,
    cdc_team_expense_bulk_update_api_view,
    timesheet_detail_api_view,
    import_timesheets_excel_api_view,
    download_timesheet_template_api_view,
    list_comments_api_view,
    create_comment_api_view,
    comment_detail_api_view,
    download_comment_attachment_api_view,
    view_comment_attachment_api_view,
    delete_comment_attachment_api_view,
    list_header_notifications_api_view,
    list_unread_task_notifications_api_view,
    list_unread_message_notifications_api_view,
    mark_task_notifications_read_api_view,
    mark_message_notifications_read_api_view,
    list_lce_costing_meta_api_view,
    list_lce_cost_details_api_view,
    create_lce_cost_detail_api_view,
    lce_cost_detail_api_view,
    download_lce_costing_template_api_view,
    import_lce_costing_excel_api_view,
    export_lce_costing_excel_api_view,
    list_lce_cost_details_by_project_api_view,
    bulk_save_lce_cost_details_api_view,
    calculate_lce_cost_index_api_view,
)

urlpatterns = [
    # auth API
    path('api/auth/csrf/', csrf_token_view, name='api-csrf'),
    path('api/auth/register/meta/', register_meta_api_view, name='api-register-meta'),
    path('api/auth/register/', register_api_view, name='api-register'),
    path('api/auth/login/', login_api_view, name='api-login'),
    path('api/auth/logout/', logout_api_view, name='api-logout'),
    path('api/auth/forgot-password/', forgot_password_api_view, name='api-forgot-password'),
    path('api/auth/reset-password/', reset_password_api_view, name='api-reset-password'),
    # users
    path('api/users/', list_users_api_view, name='api-users-list'),
    path('api/users/pending/', list_pending_registrations_api_view, name='api-users-pending'),
    path('api/users/<int:user_id>/approve/', approve_registration_api_view, name='api-users-approve'),
    path('api/users/<int:user_id>/', user_detail_api_view, name='api-users-detail'),
    # vendors
    path('api/vendors/', list_vendors_api_view, name='api-vendors-list'),
    path('api/vendors/create/', create_vendor_api_view, name='api-vendors-create'),
    path('api/vendors/<int:vendor_id>/', vendor_detail_api_view, name='api-vendors-detail'),
    # projects
    path('api/projects/', list_projects_api_view, name='api-projects-list'),
    path('api/projects/meta/', list_project_lifecycle_meta_api_view, name='api-projects-meta'),
    path('api/projects/create/', create_project_api_view, name='api-projects-create'),
    path('api/projects/<int:project_id>/', project_detail_api_view, name='api-projects-detail'),
    path('api/projects/status-options/add/', create_project_lifecycle_status_option_api_view, name='api-projects-status-add'),
    # stock purchase
    path('api/stock-purchases/', list_stock_purchases_api_view, name='api-stock-purchases-list'),
    path('api/stock-purchases/create/', create_stock_purchase_api_view, name='api-stock-purchases-create'),
    path('api/stock-purchases/<int:pk>/', stock_purchase_detail_api_view, name='api-stock-purchases-detail'),
    # stock maintenance
    path('api/stock-maintenance/', list_stock_maintenance_api_view, name='api-stock-maintenance-list'),
    path('api/stock-maintenance/meta/', list_stock_maintenance_meta_api_view, name='api-stock-maintenance-meta'),
    path('api/stock-maintenance/create/', create_stock_maintenance_api_view, name='api-stock-maintenance-create'),
    path('api/stock-maintenance/<int:pk>/', stock_maintenance_detail_api_view, name='api-stock-maintenance-detail'),
    path('api/stock-maintenance/type-options/add/', create_stock_maintenance_type_option_api_view, name='api-stock-maintenance-type-add'),
    # tasks
    path('api/tasks/', list_tasks_api_view, name='api-tasks-list'),
    path('api/tasks/meta/', list_task_meta_api_view, name='api-tasks-meta'),
    path('api/tasks/create/', create_task_api_view, name='api-tasks-create'),
    path('api/tasks/template/', download_task_template_api_view, name='api-tasks-template'),
    path('api/tasks/import/', import_tasks_excel_api_view, name='api-tasks-import'),
    path('api/tasks/<int:pk>/', task_detail_api_view, name='api-tasks-detail'),
    path('api/tasks/status-options/add/', create_task_status_option_api_view, name='api-tasks-status-add'),
    path('api/tasks/activity-options/add/', create_activity_option_api_view, name='api-tasks-activity-add'),
    path('api/tasks/project-status-options/add/', create_project_status_option_api_view, name='api-project-status-add'),
    # timesheets
    path('api/timesheets/meta/', list_timesheet_meta_api_view, name='api-timesheets-meta'),
    path('api/timesheets/', list_timesheets_api_view, name='api-timesheets-list'),
    path('api/timesheets/create/', create_timesheet_api_view, name='api-timesheets-create'),
    path('api/timesheets/import/', import_timesheets_excel_api_view, name='api-timesheets-import'),
    path('api/timesheets/template/', download_timesheet_template_api_view, name='api-timesheets-template'),
    path('api/timesheets/<int:pk>/', timesheet_detail_api_view, name='api-timesheets-detail'),
    # CDC Team Expence
    path('api/cdc-team-expence/meta/', list_cdc_team_expense_meta_api_view, name='api-cdc-team-expence-meta'),
    path('api/cdc-team-expence/', list_cdc_team_expenses_api_view, name='api-cdc-team-expence-list'),
    path('api/cdc-team-expence/create/', create_cdc_team_expense_api_view, name='api-cdc-team-expence-create'),
    path('api/cdc-team-expence/bulk-update/', cdc_team_expense_bulk_update_api_view, name='api-cdc-team-expence-bulk-update'),
    path('api/cdc-team-expence/<int:pk>/', cdc_team_expense_detail_api_view, name='api-cdc-team-expence-detail'),
    path('api/cdc-team-expence/item-options/add/', create_expense_item_option_api_view, name='api-cdc-team-expence-item-add'),
    path('api/cdc-team-expence/status-options/add/', create_expense_status_option_api_view, name='api-cdc-team-expence-status-add'),
    path('api/cdc-team-expence/session-options/add/', create_expense_session_option_api_view, name='api-cdc-team-expence-session-add'),
    # comments
    path('api/comments/', list_comments_api_view, name='api-comments-list'),
    path('api/comments/create/', create_comment_api_view, name='api-comments-create'),
    path('api/comments/<int:pk>/', comment_detail_api_view, name='api-comments-detail'),
    path('api/comment-attachments/<int:pk>/download/', download_comment_attachment_api_view, name='api-comment-attachments-download'),
    path('api/comment-attachments/<int:pk>/view/', view_comment_attachment_api_view, name='api-comment-attachments-view'),
    path('api/comment-attachments/<int:pk>/', delete_comment_attachment_api_view, name='api-comment-attachments-delete'),
    # header notifications
    path('api/notifications/header/', list_header_notifications_api_view, name='api-notifications-header'),
    path('api/notifications/tasks/unread/', list_unread_task_notifications_api_view, name='api-notifications-tasks-unread'),
    path('api/notifications/messages/unread/', list_unread_message_notifications_api_view, name='api-notifications-messages-unread'),
    path('api/notifications/tasks/mark-read/', mark_task_notifications_read_api_view, name='api-notifications-tasks-mark-read'),
    path('api/notifications/messages/mark-read/', mark_message_notifications_read_api_view, name='api-notifications-messages-mark-read'),
    # LCE costing
    path('api/lce-costing/meta/', list_lce_costing_meta_api_view, name='api-lce-costing-meta'),
    path('api/lce-costing/', list_lce_cost_details_api_view, name='api-lce-costing-list'),
    path('api/lce-costing/create/', create_lce_cost_detail_api_view, name='api-lce-costing-create'),
    path('api/lce-costing/template/', download_lce_costing_template_api_view, name='api-lce-costing-template'),
    path('api/lce-costing/import/', import_lce_costing_excel_api_view, name='api-lce-costing-import'),
    path('api/lce-costing/export/', export_lce_costing_excel_api_view, name='api-lce-costing-export'),
    path('api/lce-costing/bulk-save/', bulk_save_lce_cost_details_api_view, name='api-lce-costing-bulk-save'),
    path('api/lce-costing/by-project/<int:project_id>/', list_lce_cost_details_by_project_api_view, name='api-lce-costing-by-project'),
    path('api/lce-costing/cost-index/calculate/', calculate_lce_cost_index_api_view, name='api-lce-costing-cost-index-calculate'),
    path('api/lce-costing/<int:pk>/', lce_cost_detail_api_view, name='api-lce-costing-detail'),
]