from django.urls import path
from .views import (
    LoginPageView,
    RegisterView,
    csrf_token_view,
    approve_registration_api_view,
    create_project_api_view,
    create_project_lifecycle_status_option_api_view,
    create_vendor_api_view,
    list_users_api_view,
    list_pending_registrations_api_view,
    list_projects_api_view,
    list_project_lifecycle_meta_api_view,
    list_vendors_api_view,
    login_api_view,
    logout_api_view,
    project_detail_api_view,
    register_api_view,
    register_meta_api_view,
    user_detail_api_view,
    vendor_detail_api_view,
    list_stock_purchases_api_view,
    create_stock_purchase_api_view,
    stock_purchase_detail_api_view,
    list_stock_maintenance_api_view,
    list_stock_maintenance_meta_api_view,
    create_stock_maintenance_api_view,
    create_stock_maintenance_type_option_api_view,
    stock_maintenance_detail_api_view,
    list_tasks_api_view,
    list_task_meta_api_view,
    create_task_api_view,
    task_detail_api_view,
    create_task_status_option_api_view,
    create_project_status_option_api_view,
)

urlpatterns = [
    path('', LoginPageView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginPageView.as_view(), name='login-page'),
    # auth API
    path('api/auth/csrf/', csrf_token_view, name='api-csrf'),
    path('api/auth/register/meta/', register_meta_api_view, name='api-register-meta'),
    path('api/auth/register/', register_api_view, name='api-register'),
    path('api/auth/login/', login_api_view, name='api-login'),
    path('api/auth/logout/', logout_api_view, name='api-logout'),
    # users
    path('api/users/', list_users_api_view, name='api-users-list'),
    path('api/users/pending/', list_pending_registrations_api_view, name='api-users-pending'),
    path('api/users/<int:user_id>/approve/', approve_registration_api_view, name='api-users-approve'),
    path('api/users/<int:user_id>/', user_detail_api_view, name='api-users-detail'),
    # vendors
    path('api/vendors/', list_vendors_api_view, name='api-vendors-list'),
    path('api/vendors/create/', create_vendor_api_view, name='api-vendors-create'),
    path('api/vendors/<int:vendor_id>/', vendor_detail_api_view, name='api-vendors-detail'),
    # projects
    path('api/projects/', list_projects_api_view, name='api-projects-list'),
    path('api/projects/meta/', list_project_lifecycle_meta_api_view, name='api-projects-meta'),
    path('api/projects/create/', create_project_api_view, name='api-projects-create'),
    path('api/projects/<int:project_id>/', project_detail_api_view, name='api-projects-detail'),
    path('api/projects/status-options/add/', create_project_lifecycle_status_option_api_view, name='api-projects-status-add'),
    # stock purchase
    path('api/stock-purchases/', list_stock_purchases_api_view, name='api-stock-purchases-list'),
    path('api/stock-purchases/create/', create_stock_purchase_api_view, name='api-stock-purchases-create'),
    path('api/stock-purchases/<int:pk>/', stock_purchase_detail_api_view, name='api-stock-purchases-detail'),
    # stock maintenance
    path('api/stock-maintenance/', list_stock_maintenance_api_view, name='api-stock-maintenance-list'),
    path('api/stock-maintenance/meta/', list_stock_maintenance_meta_api_view, name='api-stock-maintenance-meta'),
    path('api/stock-maintenance/create/', create_stock_maintenance_api_view, name='api-stock-maintenance-create'),
    path('api/stock-maintenance/<int:pk>/', stock_maintenance_detail_api_view, name='api-stock-maintenance-detail'),
    path('api/stock-maintenance/type-options/add/', create_stock_maintenance_type_option_api_view, name='api-stock-maintenance-type-add'),
    # tasks
    path('api/tasks/', list_tasks_api_view, name='api-tasks-list'),
    path('api/tasks/meta/', list_task_meta_api_view, name='api-tasks-meta'),
    path('api/tasks/create/', create_task_api_view, name='api-tasks-create'),
    path('api/tasks/<int:pk>/', task_detail_api_view, name='api-tasks-detail'),
    path('api/tasks/status-options/add/', create_task_status_option_api_view, name='api-tasks-status-add'),
    path('api/tasks/project-status-options/add/', create_project_status_option_api_view, name='api-project-status-add'),
]